### ISSUE TITLE
M3 - Individual Android Exercise

### ISSUE THREAD

**Issue by theresaming** [theresaming/CS2340-M1#3]

**Comment by theresaming** [comment]
## Tasks 
- [ ] To support the class standing, we will first need to create a new class named ClassStanding which is an enum with the values FRESHMAN, SOPHOMORE, JUNIOR, and SENIOR. Give each class a two character representation "FR", "SO", "JR" and "SR".

- [ ] Add an attribute to Student which holds the ClassStanding enum.

- [ ] Add getter and setter for the ClassStanding.

- [ ] Make a new 3 param constructor which includes name, major and class standing. Keep the old two param constructor for backwards compatibility and use constructor chaining to give a default class standing of Freshman.

- [ ] Change the toString method to contain the class standing .

Grading Criteria
enum for ClassStanding ....................................10
attribute added in Student ................................05
getter/setter .............................................10
new constructor ...........................................05
toString ..................................................05
widget added to dialog ....................................15
list shows required info...................................05
student added is in list...................................10
dialog displays required default information ..............10
dialog updates model ......................................15
data validation (if required) .............................10 (constrained inputs get points automatically)
